version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888
    ports:
        - 22181:22181

  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092

  kafka-2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092

  kafka-3:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:39092

  producer:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:22181
    command: bash -c "sleep 60 && kafka-topics --create --topic my_topic --partitions 1 --replication-factor 3 --if-not-exists --zookeeper zookeeper:22181 && while true; do date | kafka-console-producer --broker-list kafka-1:39092,kafka-2:29092,kafka-3:19092 --topic my_topic; echo 'sent'; sleep 1; done "
  consumer:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:22181
    command: bash -c "sleep 6 && kafka-console-consumer --topic my_topic --bootstrap-server kafka-1:19092,kafka-2:29092,kafka-3:39092"